image: Visual Studio 2017

environment:
  MICROPY_CPYTHON3: c:/python34/python.exe
  MICROPYPATH: c:/projects/micropython/ports/windows
  matrix:
    - FullTypeCheck: 0
    - FullTypeCheck: 1

init:
- ps: |
    # Set build version number to commit to be travis-like
    Update-AppveyorBuild -Version $env:appveyor_repo_commit.substring(0,8)

configuration:
- Debug
- Release

platform:
- Win32
- x64

build_script:
- ps: |
    Write-Host "platform=$env:platform configuration=$env:configuration"

    git clone -q --depth 1 --branch=windows-pyd https://github.com/stinos/micropython ../micropython

    # Not 100% sure why WindowsTargetPlatformVersion etc are needed in Powershell build scripts,
    # but not when running cmd scripts or when building projects directly. But without it result is
    # "The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found"
    foreach ($projectDir in @('../micropython/ports/windows', './')) {
    @"
    <Project>
      <PropertyGroup>
        <WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>
        <PlatformToolset>v141</PlatformToolset>
      </PropertyGroup>
      <ItemDefinitionGroup>
        <ClCompile>
          <PreProcessorDefinitions>UPYWRAP_FULLTYPECHECK=$env:FullTypeCheck;%(PreProcessorDefinitions)</PreProcessorDefinitions>
        </ClCompile>
      </ItemDefinitionGroup>
    </Project>
    "@ | Set-Content (Join-Path $projectDir 'directory.build.props')
    }

    msbuild ../micropython/ports/windows/micropythoncore.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
    msbuild ../micropython/ports/windows/micropython.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
    msbuild micropython-wrap.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"

test_script:
- ps: |
    & $env:MICROPY_CPYTHON3 ../micropython/tests/run-tests --keep-path -d tests/py

on_failure:
- ps: |
    & $env:MICROPY_CPYTHON3 ../micropython/tests/run-tests --print-failures

skip_tags: true

deploy: off

nuget:
  disable_publish_on_pr: true

matrix:
  fast_finish: true
