sudo: required
dist: trusty
language: c++
compiler:
  - gcc

before_script:
  - sudo apt-get install -y python3 gcc-multilib pkg-config libffi-dev
  - gcc --version
  - python3 --version
  - git clone --depth=1 --branch=windows-pyd https://github.com/stinos/micropython/ ../micropython

script:
  - make test
